apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election-deployment
spec:
  selector:
    matchLabels:
      app: leader-election-app
      #coordinator: "true"
  replicas: 5
  template:
    metadata:
      labels:
        app: leader-election-app
    spec:
      containers:
        - name: leader-election
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          image: leader-election
          imagePullPolicy: Never
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RUST_BACKTRACE
              value: "1"
            - name: ROCKET_ADDRESS
              value: "0.0.0.0"
            - name: ROCKET_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
